[package]
name = "yew-immutable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-sys = "0.3.56"
yew = "0.19.3"

[dev-dependencies]
wasm-bindgen = "0.2.79"
xtask-wasm = { path = "/home/cecile/repos/xtask-wasm", features = ["run-example"] }
