[package]
name = "imut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
map = ["indexmap"]

[dependencies]
indexmap = { version = "1", optional = true }
